language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed nguyentrungmen/udagram-api-feed:v3
  - docker tag udagram-api-user nguyentrungmen/udagram-api-user:v3
  - docker tag udagram-frontend nguyentrungmen/udagram-frontend:v3
  - docker tag reverseproxy nguyentrungmen/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push nguyentrungmen/udagram-api-feed:v3
  - docker push nguyentrungmen/udagram-api-user:v3
  - docker push nguyentrungmen/udagram-frontend:v3
  - docker push nguyentrungmen/reverseproxy:v3