language: node_js
node_js:
  - 12

services:
  - docker

script:
  # Build
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed nguyentrungmen/udagram-api-feed:v1
  - docker tag udagram-api-user nguyentrungmen/udagram-api-user:v1
  - docker tag udagram-frontend nguyentrungmen/udagram-frontend:v1
  - docker tag reverseproxy nguyentrungmen/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - docker push nguyentrungmen/udagram-api-feed:v1
  - docker push nguyentrungmen/udagram-api-user:v1
  - docker push nguyentrungmen/udagram-frontend:v1
  - docker push nguyentrungmen/reverseproxy:v1